SUPABASE_URL = "https://<key>.supabase.co"
SUPABASE_SERVICE_KEY = "<service-key>"
OPENAI_API_KEY = "<openai_api_key>"

SNOWFLAKE_ACCOUNT = "<snowflake-account>"
SNOWFLAKE_USER = "<snowflake-user>"
SNOWFLAKE_PASSWORD = "<snowflake-password>"
SNOWFLAKE_DATABASE = "SNOWFLAKE_SAMPLE_DATA"
SNOWFLAKE_SCHEMA = "TPCH_SF1"
SNOWFLAKE_WAREHOUSE = "<snowflake-warehouse>"
SNOWFLAKE_ROLE = "<snowflake-role>"
