-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER (
    C_CUSTKEY NUMBER(38,0) NOT NULL,
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY NUMBER(38,0),
    C_PHONE VARCHAR(15),
    C_ACCTBAL NUMBER(12,2),
    C_MKTSEGMENT VARCHAR(10),
    C_COMMENT VARCHAR(117),

    -- Define the primary key
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (C_CUSTKEY),

    -- Define foreign key constraint
    CONSTRAINT FK_CUSTOMER_NATION FOREIGN KEY (C_NATIONKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION(N_NATIONKEY)
);
