-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION (
    N_NATIONKEY NUMBER(38,0) NOT NULL,
    N_NAME VARCHAR(25),
    N_REGIONKEY NUMBER(38,0),
    N_COMMENT VARCHAR(152),

    -- Define the primary key
    CONSTRAINT PK_NATION PRIMARY KEY (N_NATIONKEY),

    -- Define foreign key constraint
    CONSTRAINT FK_NATION_REGION FOREIGN KEY (N_REGIONKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION(R_REGIONKEY)
);
