-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS (
    O_ORDERKEY NUMBER(38,0) NOT NULL,
    O_CUSTKEY NUMBER(38,0) NOT NULL,
    O_ORDERSTATUS VARCHAR(1),
    O_TOTALPRICE NUMBER(12,2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY VARCHAR(15),
    O_CLERK VARCHAR(15),
    O_SHIPPRIORITY NUMBER(38,0),
    O_COMMENT VARCHAR(79),

    -- Define the primary key
    CONSTRAINT PK_ORDERS PRIMARY KEY (O_ORDERKEY),

    -- Define foreign key constraint
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (O_CUSTKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER(C_CUSTKEY)
);
