-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM (
    L_ORDERKEY NUMBER(38,0) NOT NULL,
    L_PARTKEY NUMBER(38,0) NOT NULL,
    L_SUPPKEY NUMBER(38,0) NOT NULL,
    L_LINENUMBER NUMBER(38,0) NOT NULL,
    L_QUANTITY NUMBER(12,2),
    L_EXTENDEDPRICE NUMBER(12,2),
    L_DISCOUNT NUMBER(12,2),
    L_TAX NUMBER(12,2),
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT VARCHAR(25),
    L_SHIPMODE VARCHAR(10),
    L_COMMENT VARCHAR(44),

    -- Define the primary key
    CONSTRAINT PK_LINEITEM PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),

    -- Define foreign key constraints
    CONSTRAINT FK_LINEITEM_ORDER FOREIGN KEY (L_ORDERKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS(O_ORDERKEY),
    CONSTRAINT FK_LINEITEM_PART FOREIGN KEY (L_PARTKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART(P_PARTKEY),
    CONSTRAINT FK_LINEITEM_SUPPLIER FOREIGN KEY (L_SUPPKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER(S_SUPPKEY)
);
