-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION (
    R_REGIONKEY NUMBER(38,0) NOT NULL,
    R_NAME CHAR(25),
    R_COMMENT VARCHAR(152),

    -- Define the primary key
    CONSTRAINT PK_REGION PRIMARY KEY (R_REGIONKEY)
);
