-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP (
    PS_PARTKEY NUMBER(38,0) NOT NULL,
    PS_SUPPKEY NUMBER(38,0) NOT NULL,
    PS_AVAILQTY NUMBER(38,0),
    PS_SUPPLYCOST NUMBER(12,2),
    PS_COMMENT VARCHAR(199),

    -- Define the composite primary key
    CONSTRAINT PK_PARTSUPP PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),

    -- Define foreign key constraints
    CONSTRAINT FK_PARTSUPP_PART FOREIGN KEY (PS_PARTKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART(P_PARTKEY),
    CONSTRAINT FK_PARTSUPP_SUPPLIER FOREIGN KEY (PS_SUPPKEY) REFERENCES SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER(S_SUPPKEY)
);
