-- Create the table
CREATE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART (
    P_PARTKEY NUMBER(38,0) NOT NULL,
    P_NAME VARCHAR(55),
    P_MFGR VARCHAR(25),
    P_BRAND VARCHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE NUMBER(38,0),
    P_CONTAINER VARCHAR(10),
    P_RETAILPRICE NUMBER(12,2),
    P_COMMENT VARCHAR(23),

    -- Define the primary key
    CONSTRAINT PK_PART PRIMARY KEY (P_PARTKEY)
);
